spring:
  config:
    activate:
      on-profile: "prod"
build:
  version: "8.0"
cards:
  message: "Welcome to cards prod Microservice "
  contactDetails:
    name: "Amit prod Lead"
    email: "devihengnr@gmail.com"
  callSupport:
    -(555)555-1234
    -(555)523-1987
